### PR TITLE
SASS map for component colors

### PR DESCRIPTION
**Pull request by puneetjohal**
Exported all component colors into a SASS map called component-colors located in the _ColorMap.scss file. This will make it easier for future developers to swap out component colors.

Trello Card: https://trello.com/c/itRNH2ps/120-create-a-sass-map-for-searchneu

### CODE REVIEW

**Review by megandouli — APPROVED** [review]
Seems straightforward!

**Comment by puneetjohal** [comment]
I want to improve this some more based on [this ticket](https://trello.com/c/NoyNhCgB/127-add-custom-names-for-theme-colors-and-component-groups).
We should also merge this branch *after* the CPS/Law and homepage branches are merged to master, so that I can add any additional components resulting from those changes to the SASS Map.

**Review by NEUDitao — APPROVED** [review]
lgtm

**Comment by puneetjohal** [comment]
This branch would be really messy to merge with master and since we're moving away from Sass this semester, I'm going to close out this PR 🤠

**Pull request closed without merging**
